# Generated by Django 4.0.5 on 2023-03-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigyasa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pphone',
            new_name='phone',
        ),
    ]
